development:
  adapter: postgresql
  encoding: unicode
  database: database_name_development
  pool: 5
  host: localhost
  username: admin 
  password: qt95kbfg

test:
  adapter: postgresql
  encoding: unicode
  database: database_name_test
  pool: 5
  username: admin
  password: qt95kbfg

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %> 